[
  {
    "name": "TECNICO",
    "object_id": 18099105,
    "principal_id": null,
    "schema_id": 1,
    "parent_object_id": 0,
    "type": "U ",
    "type_desc": "USER_TABLE",
    "create_date": "2024-11-12T16:48:06.180Z",
    "modify_date": "2024-11-23T11:28:37.613Z",
    "is_ms_shipped": false,
    "is_published": false,
    "is_schema_published": false,
    "lob_data_space_id": 0,
    "filestream_data_space_id": null,
    "max_column_id_used": 9,
    "lock_on_bulk_load": false,
    "uses_ansi_nulls": true,
    "is_replicated": false,
    "has_replication_filter": false,
    "is_merge_published": false,
    "is_sync_tran_subscribed": false,
    "has_unchecked_assembly_data": false,
    "text_in_row_limit": 0,
    "large_value_types_out_of_row": false,
    "is_tracked_by_cdc": false,
    "lock_escalation": 0,
    "lock_escalation_desc": "TABLE",
    "is_filetable": false,
    "is_memory_optimized": false,
    "durability": 0,
    "durability_desc": "SCHEMA_AND_DATA",
    "temporal_type": 0,
    "temporal_type_desc": "NON_TEMPORAL_TABLE",
    "history_table_id": null,
    "is_remote_data_archive_enabled": false,
    "is_external": false,
    "history_retention_period": null,
    "history_retention_period_unit": null,
    "history_retention_period_unit_desc": null,
    "is_node": false,
    "is_edge": false,
    "data_retention_period": -1,
    "data_retention_period_unit": -1,
    "data_retention_period_unit_desc": "INFINITE",
    "ledger_type": 0,
    "ledger_type_desc": "NON_LEDGER_TABLE",
    "ledger_view_id": null,
    "is_dropped_ledger_table": false
  }
]